development:
  adapter: postgresql
  encoding: unicode
  database: fantasy_development
  pool: 5
  username: eric
  password: xv17xv17

test:
  adapter: postgresql
  encoding: unicode
  database: fantasy_test
  pool: 5
  username: eric
  password: xv17xv17

production:
  adapter: postgresql
  encoding: unicode
  database: fantasy_production
  pool: 5
  username: eric
  password: xv17xv17
